### ISSUE TITLE
Id does not seem available at BCB-SGS

### ISSUE THREAD

**Issue by helizao** [msperlin/GetBCBData#5]
Bom dia, 
Estava usando o pacote normalmente até ontem, porém hoje começou a aparecer este erro:

2: In .f(id = .l[[1L]][[1L]], series.name = .l[[2L]][[1L]], first.date = .l[[3L]][[1L]],  :
  
	Id 25351 does not seem available at BCB-SGS. Check it again at : <http://www.bcb.gov.br/?sgs>

Testei para outras séries e o erro persiste.
Saberiam dizer se é no BCB?

Obrigado.

**Comment by msperlin** [comment]
Bom dia Helio, 

Parece que o api tinha caído, mas já voltou ao normal.

At,
