### ISSUE TITLE
Erro ao chamar series GetBCBData::gbcbd_get_series

### ISSUE THREAD

**Issue by andrefpoli** [msperlin/GetBCBData#6]
Boa tarde,

Existe alguma forma de contornar error de chamadas pela API do Bacen SGS? Ao consultar o IBC-Br nacional e com abertura regional através de um vetor, tal como abaixo, retorna os seguintes erros. Porém, ao consultá-las individualmente (talvez pelo intervalo da consulta) e não em série pelo vetor, as séries não retornam erro. Seria então o numero de requests e o intervalo entre eles que acaba ocasionando isso?

 api_ibc = c(
    "Brasil"       = 24364,
    "Centro-Oeste" = 25382,
    "Nordeste"     = 25389,
    "Norte"        = 25407,
    "Sul"          = 25403,
    "Sudeste"      = 25395
    )
    
raw_ibc <- GetBCBData::gbcbd_get_series(
  id          = api_ibc,
  first.date  = "2003-01-27",
  use.memoise = FALSE 
  )

`Fetching Brasil [24364] from BCB-SGS from Online API Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="p
                     (right here) ------^

Fetching Centro-Oeste [25382] from BCB-SGS from Online API 
	 Found 235 observations
Fetching Nordeste [25389] from BCB-SGS from Online API 
	 Found 235 observations
Fetching Norte [25407] from BCB-SGS from Online API 
	 Found 235 observations
Fetching Sul [25403] from BCB-SGS from Online API 
	 Found 235 observations
Fetching Sudeste [25395] from BCB-SGS from Online API Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                       <?xml version="1.0" encoding="p
                     (right here) ------^

In addition: Warning messages:
1: In .f(id = .l[[1L]][[i]], series.name = .l[[2L]][[i]], first.date = .l[[3L]][[1L]],  :
  
	 Error in fetching data

2: In .f(id = .l[[1L]][[i]], series.name = .l[[2L]][[i]], first.date = .l[[3L]][[1L]],  :
  
	Id 24364 does not seem available at BCB-SGS. Check it again at : <http://www.bcb.gov.br/?sgs>

Warning messages:
1: In .f(id = .l[[1L]][[i]], series.name = .l[[2L]][[i]], first.date = .l[[3L]][[1L]],  :
  
	 Error in fetching data

2: In .f(id = .l[[1L]][[i]], series.name = .l[[2L]][[i]], first.date = .l[[3L]][[1L]],  :
  
	Id 25395 does not seem available at BCB-SGS. Check it again at : <http://www.bcb.gov.br/?sgs>`

**Comment by msperlin** [comment]
Oi Andre,

Parece ter tido alguma mudança no API do sgs/bcb.  Vou dar uma olhada assim que puder (essa semana ainda). 

At,

**Comment by msperlin** [comment]
Bom dia Andre, 

Rodei aqui os testes e tudo Ok. Me parece que era algo temporário com o SGS. Veja abaixo:

![image](https://user-images.githubusercontent.com/10583352/196940632-cc54e0d5-0e8b-4ab6-b115-2c8b53719686.png)


![image](https://user-images.githubusercontent.com/10583352/196940509-ff4db662-fd41-4928-b113-2b319458b8af.png)

**Comment by msperlin** [comment]
Vou fechar o issue.

**Comment by andrefpoli** [comment]
Bom dia Marcelo, obrigado pela atenção. É então, parece ser algo generalizado, pois tenho uma rotina rodando no github actions e toda vez que da problema é erro que dá na BCB-SGS. Entendo que deva ser uma instabilidade deles mesmo.

Muito obrigado!
