### ISSUE TITLE
Erro na data inicial

### ISSUE THREAD

**Issue by joaocosta-cnc** [msperlin/GetBCBData#7]
Eu não estou mais conseguindo coletar os dados a partir da data inicial das séries, a função sempre retorna um período a frente do dado inicial. Por exemplo, se uma série mensal começa em 01-01-2000, a função me retorna como primeiro valor 01-02-2000. 

Até onde testei isso só acontece para o valor inicial. Se eu definir alguma data intermediária da série a função seleciona corretamente a data. Abaixo segue o código que estou usando para pegar os dados da série 4503.

`dlsp_4503 <- GetBCBData::gbcbd_get_series(id = 4503, first.date = "31-12-2001")`

**Comment by msperlin** [comment]
Oi Joao,

As datas no R são no formato YYYY-MM-DD (e não DD-MM-YYYY)

dlsp_4503 <- GetBCBData::gbcbd_get_series(id = 4503, first.date = "2001-12-31")

**Comment by joaocosta-cnc** [comment]
Marcelo,

Se eu fizer o seguinte para esse código não funciona

`GetBCBData::gbcbd_get_series(id = 4639, first.date = "1991-01-31")`

**Comment by msperlin** [comment]
Aqui funcionou:

![image](https://github.com/user-attachments/assets/43af3bb9-1f2d-48ce-8524-6d624dcc0cdd)

Sugiro tentar de novo. As vezes o servidor do bcb fica instável.

**Comment by joaocosta-cnc** [comment]
É, eu acho que deve ser problema com eles. Eu tentei em várias séries, múltiplas vezes, e as vezes funcionava e as vezes não. Obrigado pela pronta ajuda!
